name: ServerStats
main: com.yourname.serverstats.ServerStats
version: 1.0.0
api-version: 1.21
author: YourName
description: Broadcasts server performance stats periodically via plugin messaging.

commands: {}

permissions: {}
