name: ServerStats
version: 1.0
main: com.yourname.serverstats.ServerStats
api-version: 1.13
authors: [YourName]
description: Server statistics plugin for Eaglercraft
commands:
  stats:
    description: Get server statistics
    usage: /<command>