name: ServerStats
main: com.yourname.serverstats.ServerStats
version: 1.0.0
api-version: 1.21                                           # â† enables modern Paper features :contentReference[oaicite:11]{index=11}
author: YourName
description: Broadcasts server performance stats via plugin messaging.
